In [1]:
import numpy as np 
import pandas as pd 
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline
import matplotlib as mpl
from matplotlib import cm

In [2]:
df=pd.read_csv('https://raw.githubusercontent.com/ammy20019/ML-stuff/master/fake_job_postings.csv')
df.head()

job_id  ... fraudulent
0       1  ...          0
1       2  ...          0
2       3  ...          0
3       4  ...          0
4       5  ...          0

[5 rows x 18 columns]

In [3]:
df.dropna(subset=['required_education'],axis=0,inplace=True)
features=['job_id', 'company_profile','description' ,	'requirements' ,	'benefits']

In [9]:
df.drop(features,axis=1,inplace=True)

In [10]:
df['location']=df['location'].astype(str)
df['department']=df['department'].astype(str)
df['salary_range']=df['salary_range'].astype(str)
df['employment_type']=df['employment_type'].astype(str)
df['required_experience']=df['required_experience'].astype(str)
df['required_education']=df['required_education'].astype(str)
df['industry']=df['industry'].astype(str)
df['function']=df['function'].astype(str)

In [11]:
categorical=df.select_dtypes('object').columns.tolist()
categorical

['location',
 'department',
 'salary_range',
 'employment_type',
 'required_experience',
 'required_education',
 'industry',
 'function']

In [8]:
df.dtypes

job_id                  int64
title                   int64
location                int64
department              int64
salary_range            int64
company_profile        object
description            object
requirements           object
benefits               object
telecommuting           int64
has_company_logo        int64
has_questions           int64
employment_type        object
required_experience    object
required_education     object
industry               object
function               object
fraudulent              int64
dtype: object

In [12]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
for i in categorical:
    df[i]=le.fit_transform(df[i])

In [13]:
df.reset_index(drop=True,inplace=True)
df.head()

title  location  department  ...  industry  function  fraudulent
0    181       134         659  ...        22        31           0
1    587       162         851  ...        50        16           0
2   2453       391         257  ...        88        20           0
3   1255      1938         851  ...        39         7           0
4    139       643         851  ...        57        18           0

[5 rows x 13 columns]

In [14]:
X=df.drop('fraudulent',axis=1)
y=df['fraudulent']

### Feature Standardization


In [22]:
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0, stratify = y)



In [23]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [24]:
X_train

array([[-1.01051531, -0.41998145,  0.63636503, ...,  2.00445964,
         0.52110984,  1.55531869],
       [ 1.24073965, -0.91799811,  0.63636503, ..., -0.7280804 ,
         1.59364017, -0.05333612],
       [-0.50835991, -1.62874375,  0.63636503, ..., -1.06964791,
        -0.19391037,  1.46594898],
       ...,
       [-1.40570935,  0.12420894,  0.63636503, ..., -0.7280804 ,
        -0.52162798,  0.12540331],
       [-0.16777246,  1.7485348 ,  0.30357236, ..., -0.7280804 ,
        -1.05789314, -0.05333612],
       [-1.43047935,  1.7485348 ,  0.30357236, ..., -0.7280804 ,
         0.01463719, -0.05333612]])

### Build ANN

In [27]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Flatten, Dense

In [28]:
model = Sequential()
model.add(Dense(X.shape[1], activation='relu', input_dim = X.shape[1]))
model.add(Dense(128, activation='relu'))
model.add(Dense(1, activation = 'sigmoid'))

In [26]:
X.shape[1]

12

In [29]:
model.compile(optimizer='adam', loss = 'binary_crossentropy', metrics=['accuracy'])

In [30]:
model.fit(X_train, y_train.to_numpy(), batch_size = 10, epochs = 10, verbose = 1)

Epoch 1/10
782/782 [==============================] - 1s 1ms/step - loss: 0.2192 - accuracy: 0.9553
Epoch 2/10
782/782 [==============================] - 1s 1ms/step - loss: 0.1423 - accuracy: 0.9602
Epoch 3/10
782/782 [==============================] - 1s 1ms/step - loss: 0.1355 - accuracy: 0.9611
Epoch 4/10
782/782 [==============================] - 1s 1ms/step - loss: 0.1364 - accuracy: 0.9583
Epoch 5/10
782/782 [==============================] - 1s 1ms/step - loss: 0.1239 - accuracy: 0.9613
Epoch 6/10
782/782 [==============================] - 1s 1ms/step - loss: 0.1199 - accuracy: 0.9623
Epoch 7/10
782/782 [==============================] - 1s 1ms/step - loss: 0.1123 - accuracy: 0.9670
Epoch 8/10
782/782 [==============================] - 1s 1ms/step - loss: 0.1042 - accuracy: 0.9686
Epoch 9/10
782/782 [==============================] - 1s 1ms/step - loss: 0.0977 - accuracy: 0.9706
Epoch 10/10
782/782 [==============================] - 1s 1ms/step - loss: 0.1097 - accuracy: 0.9654

In [33]:
y_pred = model.predict_classes(X_test)
y_pred

/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/engine/sequential.py:450: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


array([[0],
       [0],
       [0],
       ...,
       [0],
       [0],
       [0]], dtype=int32)

In [49]:
y_test

2713    0
2221    0
8879    0
8625    0
2634    1
       ..
7003    0
8445    0
3693    0
2854    0
5766    0
Name: fraudulent, Length: 1955, dtype: int64

In [35]:
model.evaluate(X_test, y_test.to_numpy())

62/62 [==============================] - 0s 1ms/step - loss: 0.1220 - accuracy: 0.9611


[0.12195726484060287, 0.9611253142356873]

In [37]:
confusion_matrix(y_test, y_pred)

array([[1866,    6],
       [  70,   13]])

In [38]:
accuracy_score(y_test, y_pred)

0.9611253196930947

In [42]:
lb = preprocessing.LabelBinarizer()
lb.fit(y_train)
roc_auc_score(lb.transform(y_test), lb.transform(y_pred))

0.5767106889094841

### Model with more layers

In [68]:
model2 = Sequential()
model2.add(Dense(X.shape[1], activation='relu', input_dim = X.shape[1]))
model2.add(Dense(128, activation='relu'))
model2.add(Dense(1, activation = 'sigmoid'))

In [69]:
model2.compile(optimizer='adam', loss = 'binary_crossentropy', metrics=['accuracy'])

In [75]:
model2.fit(X_train, y_train.to_numpy(), batch_size = 10, epochs = 100, verbose = 1)

Epoch 1/100
782/782 [==============================] - 1s 1ms/step - loss: 0.0559 - accuracy: 0.9808
Epoch 2/100
782/782 [==============================] - 1s 1ms/step - loss: 0.0563 - accuracy: 0.9803
Epoch 3/100
782/782 [==============================] - 1s 1ms/step - loss: 0.0552 - accuracy: 0.9804
Epoch 4/100
782/782 [==============================] - 1s 1ms/step - loss: 0.0539 - accuracy: 0.9802
Epoch 5/100
782/782 [==============================] - 1s 1ms/step - loss: 0.0530 - accuracy: 0.9815
Epoch 6/100
782/782 [==============================] - 1s 1ms/step - loss: 0.0529 - accuracy: 0.9815
Epoch 7/100
782/782 [==============================] - 1s 1ms/step - loss: 0.0521 - accuracy: 0.9802
Epoch 8/100
782/782 [==============================] - 1s 1ms/step - loss: 0.0513 - accuracy: 0.9818
Epoch 9/100
782/782 [==============================] - 1s 1ms/step - loss: 0.0517 - accuracy: 0.9817
Epoch 10/100
782/782 [==============================] - 1s 1ms/step - loss: 0.0508 - accura

In [76]:
y_pred = model2.predict_classes(X_test)

/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/engine/sequential.py:450: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


In [77]:
model2.evaluate(X_test, y_test.to_numpy())

62/62 [==============================] - 0s 922us/step - loss: 0.1830 - accuracy: 0.9678


[0.18297643959522247, 0.9677749276161194]

In [78]:
accuracy_score(y_test, y_pred)

0.9677749360613811

In [79]:
lb = preprocessing.LabelBinarizer()
lb.fit(y_train)
roc_auc_score(lb.transform(y_test), lb.transform(y_pred))

0.7816779940273917